### ISSUE TITLE
noNetwork error

### ISSUE THREAD

**Issue by ajag408** [ajb413/comet-liquidator#5]
Any ideas about how to get around the noNetwork error, as seen in the video walkthrough by Adam when trying to liquidate multiple positions at once (when he first demo'd running on Polygon in Test mode)?  

The script seems to stop after liquidating one position even if multiple liquidatable positions are available.

Copied the error below:

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/Users/Akash1/Desktop/comet-liquidator/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/Akash1/Desktop/comet-liquidator/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/Users/Akash1/Desktop/comet-liquidator/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
    at step (/Users/Akash1/Desktop/comet-liquidator/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/Akash1/Desktop/comet-liquidator/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/Akash1/Desktop/comet-liquidator/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

**Comment by ajag408** [comment]
One more issue I found is that when running simulateAssetChanges on Polygon like Adam did in the demo, I am getting an empty changes arr in the response, whereas in the demo the changes arr was populated with various transfers of assets.  Any ideas why the changes arr could be empty?

**Comment by Luckibn** [comment]
Hi, how are you. Have you fixed your problem? 

Can you please help me with this erro:

Error: getPoolConfig > no pool config found for 0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4
    at getPoolConfig (C:\Users\quint\comet-liquidator\scripts\liquidation_bot\liquidateUnderwaterBorrowers.ts:257:11)
    at Array.map (<anonymous>)
    at attemptLiquidation (C:\Users\quint\comet-liquidator\scripts\liquidation_bot\liquidateUnderwaterBorrowers.ts:301:38)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async liquidateUnderwaterBorrowers (C:\Users\quint\comet-liquidator\scripts\liquidation_bot\liquidateUnderwaterBorrowers.ts:504:5)
    at async main (C:\Users\quint\comet-liquidator\scripts\liquidation_bot\index.ts:113:7)

**Comment by ajag408** [comment]
Hi, gave up and haven't looked at it in a while
